<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GeneralData extends Model
{
    use HasFactory;

    protected $table = 'general_data';

    public $timestamps = false;

    // переопределение данных
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::retrieved(function($model){
            $model->price_actual = round(($model->price_actual/1000000), 2);
            $model->price_actual_to_current_day = round(($model->price_actual/1000000), 2);
            $model->price_sale = round(($model->price_sale/1000000), 2);
            $model->price_start = round(($model->price_start/1000000), 2);
            $model->square_meter_price = round(($model->square_meter_price/1000), 2);

            $model->phones = trim($model->phones);

            $model->phones = preg_replace(
                array(
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{3})[-|\s]?\)[-|\s]?(\d{3})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?(\d{3})[-|\s]?(\d{3})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{4})[-|\s]?\)[-|\s]?(\d{2})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?(\d{4})[-|\s]?(\d{2})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{4})[-|\s]?\)[-|\s]?(\d{3})[-|\s]?(\d{3})/',
                    '/[\+]?([7|8])[-|\s]?(\d{4})[-|\s]?(\d{3})[-|\s]?(\d{3})/',
                ),
                array(
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4',
                    '+7 ($2) $3-$4',
                ),
                $model->phones
            );

            $value = (($model->price_actual-$model->auction)-$model->price_sale);
            // $value = ((1650000 - 0) - 0)
            // $value = 1650000

            $direct_phone = Agent::where('id', $model->agent_id)->first();

            $model->direct_phone = $direct_phone->direct_phone;

            $model->direct_phone = trim($model->direct_phone);

            $model->direct_phone = preg_replace(
                array(
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{3})[-|\s]?\)[-|\s]?(\d{3})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?(\d{3})[-|\s]?(\d{3})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{4})[-|\s]?\)[-|\s]?(\d{2})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?(\d{4})[-|\s]?(\d{2})[-|\s]?(\d{2})[-|\s]?(\d{2})/',
                    '/[\+]?([7|8])[-|\s]?\([-|\s]?(\d{4})[-|\s]?\)[-|\s]?(\d{3})[-|\s]?(\d{3})/',
                    '/[\+]?([7|8])[-|\s]?(\d{4})[-|\s]?(\d{3})[-|\s]?(\d{3})/',
                ),
                array(
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4-$5',
                    '+7 ($2) $3-$4',
                    '+7 ($2) $3-$4',
                ),
                $model->direct_phone
            );

            if($value > 0)
                $model->percentage_income = round(($model->price_actual - $model->auction) / $value);
                // percentage_income = round((16.5 - 0) / 16.5) = 1
            else
                $model->percentage_income = 0;

            if($model->price_start){
                $model->_izmen = round(((($model->price_actual/$model->price_start)-1)*100)) . "%";
            } else {
                $model->_izmen = "";
            }

            $model->auction = $model->auction / 1000000;

            $sootn_sign = strpos($model->sootn, '-') === 0 ? '' : '+';
            $model->_soot = $sootn_sign . round($model->sootn) . '%';

            $sootn_analog_sign = strpos($model->sootn_analog, '-') === 0 ? '' : '+';
            $model->sootn_analog = $sootn_analog_sign . round($model->sootn_analog) . '%';

            if(empty($model->notRemovedAnalogAdsAvgPrice)){
                $model->notRemovedAnalogAdsCount = "";
            }else{
                $higherThanMarketPrice = $model->square_meter_price2 > $model->notRemovedAnalogAdsAvgPrice ? false : true;
                if ($model->square_meter_price) {
                    // square_meter_price = 54.28
                    // notRemovedAnalogAdsAvgPrice = 55402
                    $sootn_square_meter_price_to_analogs = (100-round(($model->notRemovedAnalogAdsAvgPrice*100)/$model->square_meter_price));
                } else {
                    $sootn_square_meter_price_to_analogs = 0;
                }

                // .($higherThanMarketPrice ? '+' : '-')
                $notRemovedAnalogAdsAvgPriceSign = strpos($sootn_square_meter_price_to_analogs, '-') === 0 ? "" : "+";
                $model->notRemovedAnalogAdsAvgPrice = $notRemovedAnalogAdsAvgPriceSign."{$sootn_square_meter_price_to_analogs}%";
            }

            // к каждой дате прибавляем 3 часа
            // т.к. время в unix метке, если переводим, то получается 21:00 часа по Гринвичу
            // Разница Москвы и Гринвича 3 часа
            // по этому к дате прибавляем 3 часа
            // и конвертируем
            $model->ad_published = $model->ad_published == 0 ? "" : Carbon::createFromTimestamp(intval($model->ad_published) + 3600 * 3)->format('d-m-Y');
            $model->ad_added = $model->ad_added == 0 ? "" : Carbon::createFromTimestamp(intval($model->ad_added) + 3600 * 3)->format('d-m-Y');
            $model->ad_remove = $model->ad_remove == 0 ? "" : Carbon::createFromTimestamp(intval($model->ad_remove) + 3600 * 3)->format('d-m-Y');

            $model->have_doubles = $model->have_doubles == 0 ? "Нет" : "Да";

            if($model->id_source == 1){ $model->id_source = "Циан"; }
            else if($model->id_source == 2){ $model->id_source = "Авито"; }
            else {$model->id_source = "ОШИБКА"; }
        });
    }
}
