<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TableSplit extends Model
{
    use HasFactory;

    protected $table = '_table_split';

    public $timestamps = false;


    // переопределение данных
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::retrieved(function($model){
            $model->title = $model->name;
            $model->dataIndex = $model->bd_name;
            $model->key = $model->bd_name;
            $model->select = 0;
            $model->select_list = [];

            if($model->bd_name == 'city'){
                $model->select = 1;
                $model->select_list = [
                    "Все города",
                    "Пустые записи",
                    "Верхошижемский район",
                    "Видное",
                    "Долгопрудный",
                    "Домодедово",
                    "Зеленогорск",
                    "Зеленоград",
                    "Клин",
                    "Колпино",
                    "Коммунарка",
                    "Королев",
                    "Красногорский район",
                    "Красное Село",
                    "Кронштадт",
                    "Ломоносов",
                    "Лукояновский район",
                    "Макарьевский район",
                    "Москва",
                    "Мытищи",
                    "Нижнеилимский район",
                    "Одинцово",
                    "Одинцовский",
                    "Павловск",
                    "Петергоф",
                    "Пушкин",
                    "Рязань",
                    "Санкт-Петербург",
                    "Сергиево-Посадский",
                    "Сестрорецк",
                    "Солнечногорск",
                    "Спасский район",
                    "Химки",
                    "Чехов",
                    "Шкотовский район"
                ];
            }

            if($model->bd_name == 'id_source'){
                $model->select = 1;
                $model->select_list = [
                    "Все записи",
                    "Авито",
                    "Циан"
                ];
            }

            if($model->bd_name == 'km_do_metro'){
                $model->select = 1;
                $model->select_list = [
                    "Все записи",
                    "До 1 км",
                    "От 1 до 2км",
                    "От 2 и более км"
                ];
            }

            if($model->bd_name == 'have_doubles'){
                $model->select = 1;
                $model->select_list = [
                    "Все записи",
                    "Да",
                    "Нет"
                ];
            }

            if($model->bd_name == 'status'){
                $model->select = 1;
                $model->select_list = [
                    "Все записи",
                    "Пустые записи",
                    "1.Оцениваем",
                    "2.Назначаем",
                    "3.На просмотр",
                    "4.Думают",
                    "8.Комитет",
                    "9. На подготовку",
                    "C1",
                    "актуально",
                    "апартаменты",
                    "далеко",
                    "ддк",
                    "ДДУ",
                    "дорого",
                    "ДУБЛЬ",
                    "мало аналогов",
                    "наше",
                    "не актуально",
                    "не берет трубку",
                    "не подходит",
                    "нет адреса",
                    "ошибка",
                    "П1",
                    "П2",
                    "П3",
                    "продали",
                    "реновация",
                    "С1",
                    "С3",
                    "сброс",
                    "сняли",
                    "торги",
                    "упустили",
                    "фейк",
                    "Без дублей и ДДУ",
                    "Исключ. 9 парам."
                ];
            }
        });
    }
}
