<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TableSplit extends Model
{
    use HasFactory;

    protected $table = '_table_split';

    public $timestamps = false;


    // переопределение данных
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::retrieved(function($model){
            $model->title = $model->name;
            $model->dataIndex = $model->bd_name;
            $model->key = $model->bd_name;
        });
    }
}
